name: env_daily_use
channels:
  - defaults
dependencies:
  - python=3.12
  - pip
  - ipython
  - ipykernel
  - notebook
  - jupyterlab
  - numpy
  - pandas
  - scipy
  - matplotlib
  - seaborn
  - scikit-learn
  - pip:
      - tensorflow
